@endPoint= http://localhost:3000

### User controller test
GET {{local endpoint}}/alpha/

###
GET {{local endpoint}}/

###
GET  {{local endpoint}}/alpha/1

###
GET  {{local endpoint}}/jwt/onlywith

###
