@endPoint= http://localhost:3000

### User controller test
GET {{local endpoint}}/alpha/

###
GET {{local endpoint}}/

###
GET  {{local endpoint}}/getJWT 

###
GET  {{local endpoint}}/getJWT/cookies/ 
###
GET {{local endpoint}}/getJWT/onlyWithJWT
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkFkYW0gU21pdGgiLCJpYXQiOjE2NzI2NjMyNzZ9.EBEKETmiONYbDfXhH3EiHEpJNk6FWzIjQVCdfqZ4snE"
}
